<?php
session_start();
require_once __DIR__ . '/config/database.php';

if (isset($_GET['logout'])) {
    session_destroy();
    header('Location: index.php');
    exit;
}

$loginError = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'login') {
    $email = trim($_POST['email'] ?? '');
    $password = $_POST['password'] ?? '';
    $user = db_one('SELECT id, nome, email, senha, perfil FROM usuarios WHERE email = ?', [$email]);
    if ($user && password_verify($password, $user['senha'])) {
        $_SESSION['user'] = ['id' => $user['id'], 'nome' => $user['nome'], 'email' => $user['email'], 'perfil' => $user['perfil']];
        header('Location: index.php');
        exit;
    }
    $loginError = 'E-mail ou senha inválidos.';
}

if (!isset($_SESSION['user'])):
?>
<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>HotelSys | Acesso</title><link rel="stylesheet" href="assets/css/style.css"></head>
<body class="login-page">
  <main class="login-shell">
    <section class="login-visual"><div class="brand brand-light"><span class="brand-mark">HS</span><span>HotelSys</span></div><div class="visual-copy"><span class="eyebrow">HOTEL SENAI PALACE</span><h1>Operação hoteleira, <em>sem complicação.</em></h1><p>Uma visão clara para receber melhor, todos os dias.</p></div><div class="visual-footer"><span>Hospedagem inteligente</span><span>•</span><span>Experiência SENAI</span></div></section>
  <section class="login-form-area"><div class="login-form-wrap"><div class="mobile-brand brand"><span class="brand-mark">HS</span><span>HotelSys</span></div><span class="eyebrow">ÁREA RESTRITA</span><h2>Bem-vindo de volta</h2><p class="muted">Entre com suas credenciais para acessar a central.</p><?php if ($loginError): ?><div class="alert alert-danger"><?= htmlspecialchars($loginError) ?></div><?php endif; ?><form method="post"><input type="hidden" name="action" value="login"><label>E-mail profissional<input type="email" name="email" placeholder="voce@senai.br" required autofocus></label><label>Senha<div class="password-field"><input type="password" name="password" placeholder="••••••••" required><button type="button" class="toggle-password" aria-label="Exibir senha">◉</button></div></label><div class="form-row"><label class="checkbox-label"><input type="checkbox" name="remember"> <span>Lembrar acesso</span></label><a href="#" onclick="showToast('Procure o administrador do sistema para redefinir sua senha.'); return false;">Esqueci minha senha</a></div><button class="btn btn-primary btn-full" type="submit">Entrar na plataforma <span>→</span></button></form><p class="login-hint">Acesso de demonstração: <strong>admin@senai.br</strong> / <strong>123456</strong></p></div><span class="copyright">© 2026 HotelSys · Hotel SENAI Palace</span></section>
</main><script src="assets/js/app.js"></script></body></html>
<?php exit; endif;

$active = $_GET['page'] ?? 'dashboard';
$stats = [
  'reservas' => db_value("SELECT COUNT(*) FROM reservas WHERE status IN ('confirmada','hospedado')") ?? 0,
  'hospedes' => db_value('SELECT COUNT(*) FROM hospedes') ?? 0,
  'quartos_livres' => db_value("SELECT COUNT(*) FROM quartos WHERE status = 'disponivel'") ?? 0,
  'ocupacao' => db_value("SELECT COUNT(*) FROM quartos WHERE status = 'ocupado'") ?? 0,
];
$reservas = db_all("SELECT r.*, h.nome AS hospede, q.numero, q.tipo FROM reservas r JOIN hospedes h ON h.id=r.hospede_id JOIN quartos q ON q.id=r.quarto_id ORDER BY r.check_in ASC LIMIT 8");
if (!$reservas) { $reservas = demo_reservas(); }
$quartos = db_all('SELECT * FROM quartos ORDER BY numero');
if (!$quartos) { $quartos = demo_quartos(); }
$hospedes = db_all('SELECT * FROM hospedes ORDER BY nome LIMIT 8');
if (!$hospedes) { $hospedes = demo_hospedes(); }
function status_label($status) { $map=['confirmada'=>'Confirmada','hospedado'=>'Hospedado','pendente'=>'Pendente','disponivel'=>'Disponível','ocupado'=>'Ocupado','manutencao'=>'Manutenção','livre'=>'Livre']; return $map[$status] ?? ucfirst($status); }
function money($n) { return 'R$ ' . number_format((float)$n, 2, ',', '.'); }
function demo_reservas(){return [['codigo'=>'RSV-2409','hospede'=>'Mariana Costa','numero'=>'204','tipo'=>'Suíte Executiva','check_in'=>'2026-09-03','check_out'=>'2026-09-06','status'=>'confirmada','valor'=>1240],['codigo'=>'RSV-2410','hospede'=>'Rafael Mendes','numero'=>'105','tipo'=>'Standard Casal','check_in'=>'2026-09-03','check_out'=>'2026-09-05','status'=>'hospedado','valor'=>680],['codigo'=>'RSV-2411','hospede'=>'Camila Nunes','numero'=>'302','tipo'=>'Luxo Twin','check_in'=>'2026-09-04','check_out'=>'2026-09-07','status'=>'confirmada','valor'=>930],['codigo'=>'RSV-2412','hospede'=>'Eduardo Lima','numero'=>'118','tipo'=>'Standard Twin','check_in'=>'2026-09-05','check_out'=>'2026-09-08','status'=>'pendente','valor'=>720]];}
function demo_quartos(){return [['numero'=>'101','tipo'=>'Standard Casal','status'=>'ocupado','diaria'=>340],['numero'=>'102','tipo'=>'Standard Twin','status'=>'disponivel','diaria'=>320],['numero'=>'103','tipo'=>'Standard Casal','status'=>'disponivel','diaria'=>340],['numero'=>'104','tipo'=>'Standard Twin','status'=>'manutencao','diaria'=>320],['numero'=>'201','tipo'=>'Luxo Casal','status'=>'ocupado','diaria'=>490],['numero'=>'202','tipo'=>'Luxo Twin','status'=>'disponivel','diaria'=>465],['numero'=>'204','tipo'=>'Suíte Executiva','status'=>'ocupado','diaria'=>620],['numero'=>'301','tipo'=>'Suíte Master','status'=>'disponivel','diaria'=>890]];}
function demo_hospedes(){return [['nome'=>'Mariana Costa','documento'=>'***.482.190-**','cidade'=>'São Paulo','ultima_visita'=>'Hoje'],['nome'=>'Rafael Mendes','documento'=>'***.109.327-**','cidade'=>'Campinas','ultima_visita'=>'Hoje'],['nome'=>'Camila Nunes','documento'=>'***.771.028-**','cidade'=>'Recife','ultima_visita'=>'02 set 2026'],['nome'=>'Eduardo Lima','documento'=>'***.334.620-**','cidade'=>'Belo Horizonte','ultima_visita'=>'28 ago 2026']];}
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>HotelSys | <?= htmlspecialchars(ucfirst($active)) ?></title><link rel="stylesheet" href="assets/css/style.css"></head><body class="app-body">
<aside class="sidebar"><div class="brand"><span class="brand-mark">HS</span><span>HotelSys</span></div><div class="hotel-tag"><span class="status-dot"></span><span>Hotel SENAI Palace</span></div><nav><p class="nav-label">VISÃO GERAL</p><a class="nav-item <?= $active==='dashboard'?'active':'' ?>" href="?page=dashboard"><span>⌂</span> Dashboard</a><a class="nav-item <?= $active==='reservas'?'active':'' ?>" href="?page=reservas"><span>▤</span> Reservas <b>12</b></a><p class="nav-label">OPERAÇÃO</p><a class="nav-item <?= $active==='quartos'?'active':'' ?>" href="?page=quartos"><span>▦</span> Quartos</a><a class="nav-item <?= $active==='hospedes'?'active':'' ?>" href="?page=hospedes"><span>♙</span> Hóspedes</a><a class="nav-item" href="#" onclick="showToast('Módulo de check-in pronto para a próxima etapa.'); return false;"><span>↗</span> Check-in</a><a class="nav-item" href="#" onclick="showToast('Módulo de check-out pronto para a próxima etapa.'); return false;"><span>↙</span> Check-out</a><p class="nav-label">SISTEMA</p><a class="nav-item" href="docs/requisitos.md" target="_blank"><span>▧</span> Documentação</a><a class="nav-item" href="#" onclick="showToast('Configurações disponíveis em breve.'); return false;"><span>⚙</span> Configurações</a></nav><div class="sidebar-bottom"><div class="mini-profile"><span class="avatar"><?= strtoupper(substr($_SESSION['user']['nome'],0,1)) ?></span><div><strong><?= htmlspecialchars($_SESSION['user']['nome']) ?></strong><small>Administrador</small></div><a href="?logout=1" title="Sair">↗</a></div></div></aside>
<main class="main-content"><header class="topbar"><button class="mobile-menu" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><div class="breadcrumb"><span>HotelSys</span><b>/</b><strong><?= htmlspecialchars(ucfirst($active)) ?></strong></div><div class="top-actions"><button class="icon-btn" onclick="showToast('Você não tem novas notificações.')">♧<i></i></button><div class="top-date">03 de setembro de 2026 <span>•</span> Quinta-feira</div></div></header>
<section class="page-content"><div class="page-heading"><div><span class="eyebrow">QUINTA-FEIRA, 03 DE SETEMBRO</span><h1><?= $active==='dashboard' ? 'Bom dia, '.$_SESSION['user']['nome'].'!' : htmlspecialchars(ucfirst($active)) ?></h1><p><?= $active==='dashboard' ? 'Aqui está o resumo da operação do Hotel SENAI Palace.' : 'Acompanhe e gerencie as informações da sua operação.' ?></p></div><button class="btn btn-primary" onclick="openModal('reservationModal')">＋ Nova reserva</button></div>
<?php if ($active==='dashboard'): ?><div class="stats-grid"><article class="stat-card"><div class="stat-top"><span>Reservas ativas</span><span class="stat-icon orange">▤</span></div><strong><?= $stats['reservas'] ?: '24' ?></strong><small class="trend up">↗ 12,5% <span>vs. mês anterior</span></small></article><article class="stat-card"><div class="stat-top"><span>Hóspedes hospedados</span><span class="stat-icon violet">♙</span></div><strong><?= $stats['hospedes'] ?: '18' ?></strong><small class="trend up">↗ 8,2% <span>vs. mês anterior</span></small></article><article class="stat-card"><div class="stat-top"><span>Quartos disponíveis</span><span class="stat-icon green">⌂</span></div><strong><?= $stats['quartos_livres'] ?: '10' ?><small class="of">/ 32</small></strong><small class="trend neutral">31,2% da capacidade total</small></article><article class="stat-card"><div class="stat-top"><span>Taxa de ocupação</span><span class="stat-icon blue">◒</span></div><strong>68<small class="of">%</small></strong><small class="trend up">↗ 4,8% <span>vs. mês anterior</span></small></article></div>
<div class="dashboard-grid"><section class="panel reservations-panel"><div class="panel-header"><div><h2>Próximas reservas</h2><p>Entradas e saídas programadas</p></div><a href="?page=reservas">Ver todas <span>→</span></a></div><div class="table-wrap"><table><thead><tr><th>HÓSPEDE</th><th>QUARTO</th><th>PERÍODO</th><th>STATUS</th><th></th></tr></thead><tbody><?php foreach($reservas as $r): ?><tr><td><div class="guest-cell"><span class="avatar avatar-sm"><?= strtoupper(substr($r['hospede'],0,1)) ?></span><div><strong><?= htmlspecialchars($r['hospede']) ?></strong><small><?= htmlspecialchars($r['codigo'] ?? 'RSV-2400') ?></small></div></div></td><td><strong><?= htmlspecialchars($r['numero']) ?></strong><small class="cell-muted"><?= htmlspecialchars($r['tipo']) ?></small></td><td><strong><?= date('d M', strtotime($r['check_in'])) ?> — <?= date('d M', strtotime($r['check_out'])) ?></strong><small class="cell-muted"><?= max(1,(strtotime($r['check_out'])-strtotime($r['check_in']))/86400) ?> noites</small></td><td><span class="badge badge-<?= $r['status'] ?>"><i></i><?= status_label($r['status']) ?></span></td><td><button class="dots" onclick="showToast('Detalhes da reserva <?= htmlspecialchars($r['codigo'] ?? 'RSV') ?>')">•••</button></td></tr><?php endforeach; ?></tbody></table></div></section><section class="panel occupancy-panel"><div class="panel-header"><div><h2>Ocupação dos quartos</h2><p>Status em tempo real</p></div><a href="?page=quartos">Gerenciar <span>→</span></a></div><div class="occupancy-visual"><div class="donut"><div><strong>68<span>%</span></strong><small>ocupados</small></div></div><div class="legend"><span><i class="dot occupied"></i>Ocupados <b>22</b></span><span><i class="dot available"></i>Disponíveis <b>10</b></span><span><i class="dot maintenance"></i>Manutenção <b>02</b></span></div></div><div class="occupancy-note"><span>☼</span><p><strong>Boa ocupação hoje.</strong><br>O movimento está acima da média para uma quinta-feira.</p></div></section></div>
<section class="panel quick-panel"><div class="panel-header"><div><h2>Ações rápidas</h2><p>Atalhos para a operação do dia</p></div></div><div class="quick-actions"><button onclick="openModal('reservationModal')"><span class="quick-icon orange">＋</span><div><strong>Nova reserva</strong><small>Cadastre uma hospedagem</small></div><b>→</b></button><button onclick="showToast('Busca de hóspedes aberta. Digite o nome ou documento.')"><span class="quick-icon violet">⌕</span><div><strong>Buscar hóspede</strong><small>Encontre um cadastro</small></div><b>→</b></button><button onclick="showToast('Check-in iniciado. Selecione uma reserva confirmada.')"><span class="quick-icon green">↗</span><div><strong>Realizar check-in</strong><small>Registre uma chegada</small></div><b>→</b></button><button onclick="showToast('Relatório diário preparado para exportação.')"><span class="quick-icon blue">▥</span><div><strong>Relatório do dia</strong><small>Veja o movimento completo</small></div><b>→</b></button></div></section>
<?php elseif ($active==='quartos'): ?><div class="filter-bar"><div class="search-box">⌕ <input placeholder="Buscar por número ou tipo..." oninput="filterRows(this.value, 'roomsTable')"></div><select><option>Todos os status</option><option>Disponível</option><option>Ocupado</option><option>Manutenção</option></select></div><section class="panel"><div class="table-wrap"><table id="roomsTable"><thead><tr><th>QUARTO</th><th>TIPO</th><th>DIÁRIA</th><th>STATUS</th><th>AÇÃO</th></tr></thead><tbody><?php foreach($quartos as $q): ?><tr><td><strong class="room-number"><?= htmlspecialchars($q['numero']) ?></strong></td><td><?= htmlspecialchars($q['tipo']) ?></td><td><?= money($q['diaria']) ?></td><td><span class="badge badge-<?= $q['status'] ?>"><i></i><?= status_label($q['status']) ?></span></td><td><button class="btn btn-ghost btn-sm" onclick="showToast('Quarto <?= htmlspecialchars($q['numero']) ?> selecionado.')">Ver detalhes</button></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php elseif ($active==='hospedes'): ?><div class="filter-bar"><div class="search-box">⌕ <input placeholder="Buscar hóspede ou documento..." oninput="filterRows(this.value, 'guestsTable')"></div><button class="btn btn-primary" onclick="showToast('Formulário de novo hóspede disponível na próxima etapa.')">＋ Novo hóspede</button></div><section class="panel"><div class="table-wrap"><table id="guestsTable"><thead><tr><th>HÓSPEDE</th><th>DOCUMENTO</th><th>CIDADE</th><th>ÚLTIMA VISITA</th><th></th></tr></thead><tbody><?php foreach($hospedes as $h): ?><tr><td><div class="guest-cell"><span class="avatar avatar-sm"><?= strtoupper(substr($h['nome'],0,1)) ?></span><strong><?= htmlspecialchars($h['nome']) ?></strong></div></td><td><?= htmlspecialchars($h['documento']) ?></td><td><?= htmlspecialchars($h['cidade']) ?></td><td><?= htmlspecialchars($h['ultima_visita']) ?></td><td><button class="dots" onclick="showToast('Perfil de <?= htmlspecialchars($h['nome']) ?>')">•••</button></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php else: ?><div class="filter-bar"><div class="search-box">⌕ <input placeholder="Buscar por hóspede, código ou quarto..." oninput="filterRows(this.value, 'reservationsTable')"></div><select><option>Todos os status</option><option>Confirmada</option><option>Hospedado</option><option>Pendente</option></select></div><section class="panel"><div class="table-wrap"><table id="reservationsTable"><thead><tr><th>HÓSPEDE</th><th>QUARTO</th><th>PERÍODO</th><th>VALOR</th><th>STATUS</th><th></th></tr></thead><tbody><?php foreach($reservas as $r): ?><tr><td><div class="guest-cell"><span class="avatar avatar-sm"><?= strtoupper(substr($r['hospede'],0,1)) ?></span><div><strong><?= htmlspecialchars($r['hospede']) ?></strong><small><?= htmlspecialchars($r['codigo'] ?? 'RSV-2400') ?></small></div></div></td><td><?= htmlspecialchars($r['numero']) ?><small class="cell-muted"><?= htmlspecialchars($r['tipo']) ?></small></td><td><?= date('d/m/Y', strtotime($r['check_in'])) ?> — <?= date('d/m/Y', strtotime($r['check_out'])) ?></td><td><?= money($r['valor'] ?? 0) ?></td><td><span class="badge badge-<?= $r['status'] ?>"><i></i><?= status_label($r['status']) ?></span></td><td><button class="dots" onclick="showToast('Detalhes da reserva <?= htmlspecialchars($r['codigo'] ?? 'RSV') ?>')">•••</button></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?></section></main>
<div class="modal-backdrop" id="reservationModal"><div class="modal"><button class="modal-close" onclick="closeModal('reservationModal')">×</button><span class="eyebrow">NOVA HOSPEDAGEM</span><h2>Criar reserva</h2><p class="muted">Preencha os dados essenciais para iniciar uma nova reserva.</p><form onsubmit="event.preventDefault(); closeModal('reservationModal'); showToast('Reserva criada com sucesso.');"><label>Hóspede<input required placeholder="Nome completo"></label><div class="two-cols"><label>Check-in<input type="date" required value="2026-09-03"></label><label>Check-out<input type="date" required value="2026-09-05"></label></div><label>Quarto<select required><option value="">Selecione um quarto disponível</option><option>102 — Standard Twin</option><option>103 — Standard Casal</option><option>202 — Luxo Twin</option><option>301 — Suíte Master</option></select></label><button class="btn btn-primary btn-full" type="submit">Confirmar reserva <span>→</span></button></form></div></div><div id="toast" class="toast"></div><script src="assets/js/app.js"></script></body></html>
