/**
 * Sinal de Concreto: entrada assimétrica de comando e vitrine de obra para iniciar a contratação.
 */
import { PublicLayout } from "@/components/SiteShell";
import { MachineCard } from "@/components/MachineCard";
import { Button } from "@/components/ui/button";
import { heroImage, machines, providerImage } from "@/lib/marketplace";
import { ArrowRight, BadgeCheck, Building2, Check, ChevronRight, CircleDollarSign, Construction, MapPin, Search, ShieldCheck, Tractor, Truck, Warehouse, Wrench } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";

const categories = [
  { name: "Tratores", text: "Preparo, tração e apoio rural", icon: Tractor, count: "18 opções" },
  { name: "Escavadeiras", text: "Escavação e terraplenagem", icon: Construction, count: "26 opções" },
  { name: "Retroescavadeiras", text: "Obras urbanas e valas", icon: Wrench, count: "14 opções" },
  { name: "Guindastes", text: "Içamento e montagem", icon: Warehouse, count: "9 opções" },
  { name: "Caminhões", text: "Transporte e remoção", icon: Truck, count: "22 opções" },
  { name: "Outras máquinas", text: "Opções para demandas específicas", icon: Building2, count: "11 opções" },
];

export default function Home() {
  const [, setLocation] = useLocation(); const [need, setNeed] = useState(""); const [where, setWhere] = useState(""); const [favorites, setFavorites] = useState<number[]>(() => { try { return JSON.parse(localStorage.getItem("maqfacil-favoritos") || "[]"); } catch { return []; } });
  const search = (event: React.FormEvent) => { event.preventDefault(); const params = new URLSearchParams(); if (need) params.set("q", need); if (where) params.set("local", where); setLocation(`/maquinas?${params.toString()}`); };
  const toggleFavorite = (id: number) => setFavorites((current) => { const next = current.includes(id) ? current.filter((favorite) => favorite !== id) : [...current, id]; localStorage.setItem("maqfacil-favoritos", JSON.stringify(next)); return next; });
  return <PublicLayout>
    <section className="relative overflow-hidden bg-[#252724] text-white"><img src={heroImage} alt="Máquinas pesadas em operação numa obra" className="absolute inset-0 h-full w-full object-cover object-[62%_center] opacity-75" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(28,30,27,0.96)_0%,rgba(28,30,27,0.83)_37%,rgba(28,30,27,0.25)_74%,rgba(28,30,27,0.16)_100%)]" />
      <div className="relative mx-auto grid min-h-[630px] max-w-[1440px] items-end px-5 pb-12 pt-20 md:px-8 lg:grid-cols-[minmax(0,610px)_1fr] lg:pb-16 lg:pt-24"><div className="reveal-up"><div className="mb-6 flex items-center gap-3"><span className="h-px w-10 bg-[#F4B400]" /><p className="text-xs font-extrabold tracking-[0.2em] text-[#F4B400]">OPERAÇÃO SEM COMPLICAÇÃO</p></div><h1 className="font-display text-5xl font-bold uppercase leading-[0.88] tracking-tight sm:text-6xl md:text-7xl">Encontre a máquina certa <span className="text-[#F4B400]">para o seu projeto.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-white/76 md:text-lg">Conectamos você aos prestadores de serviços com máquinas pesadas de forma rápida, organizada e transparente.</p>
        <form onSubmit={search} className="mt-9 bg-[#FCFBF8] p-3 shadow-[12px_12px_0_rgba(244,180,0,0.9)]"><div className="grid gap-2 lg:grid-cols-[1.22fr_1fr_auto]"><label className="flex items-center gap-3 border border-[#DFDBD1] bg-white px-3 py-3 text-[#252724]"><Search className="h-5 w-5 text-[#B88700]" /><span className="min-w-0 flex-1"><span className="block text-[0.62rem] font-extrabold tracking-[0.14em] text-[#7A7B74]">O QUE VOCÊ PRECISA?</span><input value={need} onChange={(event) => setNeed(event.target.value)} className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-[#A3A39A]" placeholder="Ex.: retroescavadeira" /></span></label><label className="flex items-center gap-3 border border-[#DFDBD1] bg-white px-3 py-3 text-[#252724]"><MapPin className="h-5 w-5 text-[#B88700]" /><span className="min-w-0 flex-1"><span className="block text-[0.62rem] font-extrabold tracking-[0.14em] text-[#7A7B74]">ONDE?</span><input value={where} onChange={(event) => setWhere(event.target.value)} className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-[#A3A39A]" placeholder="Cidade ou região" /></span></label><Button type="submit" className="button-signal h-auto min-h-14 px-6">Buscar máquinas<ArrowRight className="ml-2 h-4 w-4" /></Button></div></form>
        <div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs text-white/66"><span className="font-bold text-white/80">BUSCAS POPULARES:</span>{["Escavadeira", "Guindaste", "Trator", "Caminhão basculante"].map((item) => <button onClick={() => { setNeed(item); }} className="hover:text-[#F4B400]" key={item}>{item}</button>)}</div></div><div className="hidden justify-end lg:flex"><div className="border-l border-[#F4B400] pl-5"><p className="font-display text-5xl font-bold text-[#F4B400]">01</p><p className="mt-2 max-w-[150px] text-sm leading-5 text-white/70">Comece com uma busca clara. Compare depois.</p></div></div></div>
    </section>
    <section className="border-b border-[#E1DDD3] bg-[#EEEAE0]"><div className="mx-auto grid max-w-[1440px] grid-cols-2 divide-x divide-y divide-[#D9D3C6] px-5 sm:grid-cols-4 sm:divide-y-0 md:px-8"><div className="py-6 sm:py-8"><p className="font-display text-4xl font-bold">+100</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.1em] text-[#6D6E66]">Máquinas listadas</p></div><div className="px-5 py-6 sm:px-8 sm:py-8"><p className="font-display text-4xl font-bold">12</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.1em] text-[#6D6E66]">Categorias</p></div><div className="py-6 sm:px-8 sm:py-8"><p className="font-display text-4xl font-bold">+40</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.1em] text-[#6D6E66]">Prestadores ativos</p></div><div className="px-5 py-6 sm:px-8 sm:py-8"><p className="font-display text-4xl font-bold">24h</p><p className="mt-1 text-xs font-bold uppercase tracking-[0.1em] text-[#6D6E66]">Para organizar pedidos</p></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 md:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="section-eyebrow">POR TIPO DE OPERAÇÃO</p><h2 className="mt-3 max-w-md font-display text-5xl font-bold leading-[0.9] uppercase md:text-6xl">Encontre o equipamento ideal</h2></div><Link href="/maquinas" className="group flex items-center gap-2 self-start text-sm font-bold text-[#3E403B] md:self-auto">Ver todos os equipamentos <span className="grid h-8 w-8 place-items-center bg-[#F4B400] transition group-hover:translate-x-1"><ChevronRight className="h-4 w-4" /></span></Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{categories.map(({ name, text, icon: Icon, count }, index) => <Link href={`/maquinas?category=${encodeURIComponent(name)}`} key={name} className="group relative flex min-h-40 flex-col justify-between overflow-hidden border border-[#E5E1D8] bg-[#FCFBF8] p-5 transition hover:border-[#B88700] hover:shadow-[7px_7px_0_#F4B400]"><span className="absolute right-0 top-0 px-4 py-3 font-display text-4xl font-bold text-[#EAE5DA] transition group-hover:text-[#F4B400]/30">0{index + 1}</span><Icon className="h-8 w-8 text-[#B88700]" /><div><h3 className="font-display text-2xl font-bold uppercase">{name}</h3><p className="mt-1 text-sm text-[#676861]">{text}</p><p className="mt-3 text-xs font-extrabold uppercase tracking-[0.11em] text-[#9A7200]">{count} <span className="ml-1">→</span></p></div></Link>)}</div></section>
    <section className="bg-[#E9E5DA] py-20"><div className="mx-auto max-w-[1440px] px-5 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="section-eyebrow">EM DESTAQUE NA REGIÃO</p><h2 className="mt-3 font-display text-5xl font-bold uppercase leading-[0.9] md:text-6xl">Prontos para entrar em campo</h2></div><p className="max-w-sm text-sm leading-6 text-[#676861]">Explore equipamentos e acesse dados objetivos antes de solicitar seu orçamento.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{machines.slice(0, 3).map((machine) => <MachineCard key={machine.id} machine={machine} favorite={favorites.includes(machine.id)} onFavorite={() => toggleFavorite(machine.id)} />)}</div></div></section>
    <section id="como-funciona" className="relative overflow-hidden bg-[#252724] py-20 text-white"><div className="absolute right-0 top-0 h-full w-1/3 bg-[linear-gradient(135deg,transparent_0%,rgba(244,180,0,0.08)_100%)]" /><div className="relative mx-auto grid max-w-[1440px] gap-14 px-5 md:px-8 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="section-eyebrow">FLUXO DE CONTRATAÇÃO</p><h2 className="mt-4 font-display text-5xl font-bold uppercase leading-[0.9] md:text-6xl">Do primeiro filtro ao serviço contratado.</h2><p className="mt-6 max-w-sm leading-7 text-white/65">Uma sequência pensada para reduzir desencontros e organizar o que importa antes da contratação.</p></div><div className="grid gap-x-7 gap-y-9 sm:grid-cols-2">{[["01", "Encontre", "Pesquise a máquina ou o serviço que sua operação pede."], ["02", "Compare", "Veja preço, localização, disponibilidade e escopo."], ["03", "Solicite", "Envie os dados essenciais para receber uma proposta."], ["04", "Contrate", "Organize a negociação e acompanhe os próximos passos."]].map(([number, title, text]) => <div key={number} className="border-t border-white/18 pt-4"><p className="font-display text-4xl font-bold text-[#F4B400]">{number}</p><h3 className="mt-3 font-display text-2xl font-bold uppercase">{title}</h3><p className="mt-2 text-sm leading-6 text-white/62">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 md:px-8"><div className="grid overflow-hidden bg-[#252724] text-white lg:grid-cols-[0.95fr_1.05fr]"><div className="relative min-h-[360px]"><img src={providerImage} alt="Operador diante de uma máquina pesada" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/10 to-transparent" /></div><div className="p-8 sm:p-12"><p className="section-eyebrow">SOU PRESTADOR</p><h2 className="mt-4 max-w-lg font-display text-5xl font-bold uppercase leading-[0.9] md:text-6xl">Sua máquina pode abrir novos caminhos.</h2><p className="mt-6 max-w-md text-sm leading-7 text-white/66">Centralize seus equipamentos, receba solicitações de serviço e mantenha sua operação organizada em um único lugar.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Divulgue seus equipamentos", "Receba novos pedidos", "Organize sua agenda", "Acompanhe orçamentos"].map((item) => <p key={item} className="flex items-center gap-2 text-sm font-semibold"><Check className="h-4 w-4 text-[#F4B400]" />{item}</p>)}</div><Link href="/prestadores" className="mt-9 inline-block"><Button className="button-signal h-12 px-5">Conhecer a área do prestador<ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div></div></section>
    <section className="border-t border-[#E3DED2] bg-[#FCFBF8]"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-16 md:grid-cols-3 md:px-8">{[[ShieldCheck, "Informação centralizada", "Detalhes do equipamento, preço estimado e dados do prestador no mesmo fluxo."], [MapPin, "Decisão por proximidade", "Use localização e distância para encontrar opções mais adequadas à sua obra."], [CircleDollarSign, "Comparação prática", "Organize os dados que você precisa avaliar antes de fazer uma solicitação."]].map(([Icon, title, text]) => <div key={title as string} className="border-l-2 border-[#F4B400] pl-5"><Icon className="h-6 w-6 text-[#B88700]" /><h3 className="mt-5 font-display text-2xl font-bold uppercase">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#676861]">{text as string}</p></div>)}</div></section>
  </PublicLayout>;
}
